insert into users (full_name, user_name, email, phone, website) values ('Leanne Graham', 'Bret', 'Sincere@april.biz', '1-770-736-8031 x56442', 'hildegard.org');
insert into users (full_name, user_name, email, phone, website) values ('Ervin Howell', 'Antonette', 'Shanna@melissa.tv', '010-692-6593 x09125', 'anastasia.net');
insert into users (full_name, user_name, email, phone, website) values ('Clementine Bauch', 'Samantha', 'Nathan@yesenia.net', '1-463-123-4447', 'ramiro.info');
insert into users (full_name, user_name, email, phone, website) values ('Patricia Lebsack', 'Karianne', 'Julianne.OConner@kory.org', '493-170-9623 x156', 'kale.biz');
insert into users (full_name, user_name, email, phone, website) values ('Chelsey Dietrich', 'Kamren', 'Lucio_Hettinger@annie.ca', '(254)954-1289', 'demarco.info');
insert into users (full_name, user_name, email, phone, website) values ('Mrs. Dennis Schulist', 'Leopoldo_Corkery', 'Karley_Dach@jasper.info', '1-477-935-8478 x6430', 'ola.org');
insert into users (full_name, user_name, email, phone, website) values ('Kurtis Weissnat', 'Elwyn.Skiles', 'Telly.Hoeger@billy.biz', '210.067.6132', 'elvis.io');
insert into users (full_name, user_name, email, phone, website) values ('Nicholas Runolfsdottir V', 'Maxime_Nienow', 'Sherwood@rosamond.me', '586.493.6943 x140', 'jacynthe.com');
insert into users (full_name, user_name, email, phone, website) values ('Glenna Reichert', 'Delphine', 'Chaim_McDermott@dana.io', '(775)976-6794 x41206', 'conrad.com');
insert into users (full_name, user_name, email, phone, website) values ('Clementina DuBuque', 'Moriah.Stanton', 'Rey.Padberg@karina.biz', '024-648-3804', 'ambrose.net');